### ISSUE TITLE
Cannot find a suitable audio player?

### ISSUE THREAD

**Issue by Grey-Lancaster** [T-vK/WLED-Fireworks-Sound-Effect-Companion#1]
My Win 8.1 defaults to windows media player.  files do play if I dbl click them.  Any ideas?
Thanks,
Grey

C:\WLED-Fireworks-Sound-Effect-Companion>node ./server.js
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
INFO: Could not find files for the given pattern(s).
Attempting to connect with your ESP via 'ws://192.168.1.36/ws'.
Change the IP address in the server.js if it doesn't match your ESP's.
Make sure you've got the WLED firmware flashed to the ESP and enabled the Firew
rk 1d animation.
WebSocket Client Connected
Rocket launch detected! Playing launch sound!
C:\WLED-Fireworks-Sound-Effect-Companion\server.js:39
                            if (err) throw err
                                     ^

Error: Couldn't find a suitable audio player
    at Play.play (C:\WLED-Fireworks-Sound-Effect-Companion\node_modules\←[4mpla
-sound←[24m\index.js:34:19)
    at Timeout._onTimeout (C:\WLED-Fireworks-Sound-Effect-Companion\server.js:3
:32)
←[90m    at listOnTimeout (internal/timers.js:549:17)←[39m
←[90m    at processTimers (internal/timers.js:492:7)←[39m

C:\WLED-Fireworks-Sound-Effect-Companion>

**Comment by T-vK** [comment]
Thanks for the bug report. I should probably use a different audio library for better windows support.
You can make it work by installing `mplayer` and adding it to a directory in PATH. More info on that:
https://github.com/shime/play-sound/issues/39

**Comment by Grey-Lancaster** [comment]
well I cheated and put mplayer win the wled-firworks directory
It now plays the sounds though once it starts the launch does not seem to wait for the explosion.  My explosin.mp3 may be to long.
As well my lights do not seem to do anything different.  Is there a udp port or some config I need to do in WLED?
Thanks for the help
Grey

**Comment by T-vK** [comment]
In WLED you have to go Effects and select "Fireworks 1D". WLED will handle the animation on its own. The sound companion will simply spy on the running WLED animation predict when an explosion or launch happens and react with playing a sound accordingly.

**Comment by Grey-Lancaster** [comment]
Okay, I had selected plain fireworks.  I need better sounds perhaps or figure to how to delay between launch and explosion.  My explosion seems to play all the time. But I am making progress :-)
[sounds.zip](https://github.com/T-vK/WLED-Fireworks-Sound-Effect-Companion/files/7810153/sounds.zip)

**Comment by T-vK** [comment]
I will find some free audio files for you. It's a bit tricky because I need to be careful about licensing and I will probably also have to edit the files slightly to make sure the explosion starts immediately without delay.

**Comment by Grey-Lancaster** [comment]
Thanks so much !
Grey

**Comment by T-vK** [comment]
I found some free sound effects, edited them accordingly and added them to the repo. Tell me if this works for you.

**Comment by Grey-Lancaster** [comment]
Perfect :-) 
Now we have to get node.js sound to run on an esp8266 LOL
I ordered some shields with an sd card and some little speakers to make an mp3 player but have not gotten around to that yet.
Great project.  Thanks for sharing it
Grey

**Comment by T-vK** [comment]
Yeah that would be great. I actually have an ESP32-Audio-kit board which has and sd card reader, audio jacks for input and output, as well as 2 built-in mics. It would be pretty neat if we could add the sound effects directly to the source.
But it would probably be very time consuming to implement.
I think most people would prefer the external method because if you only have one set of speakers you don't want to be plugging your speakers into different devices all the time.

One thing I am considering is adding this as a feature to the web interface of WLED. This way you don't have to set up node.js, you could just open WLED in your browser and it could play the sound through your browser to your speakers. Theoretically, this would be relatively straight forward to implement, but would probably cause issues for lots of people because they would either need an Internet connection that the web interface can use to download and play the files when needed, or they would need an SD card with the effect files. Also in the latter case a lot of additional programing would be required to make the files available for the web interface.

**Comment by Grey-Lancaster** [comment]
I think I just need to find my BT dongle and Bluetooth speakers.
Send me an email if you come up with something to try for you,
Thanks again,
grey@smallbizserver.com

**Comment by T-vK** [comment]
No problem. Glad to see it's useful to someone.
I think Bluetooth will open a whole new can of issues, because Bluetooth always adds significant latency to the audio, so your sound effects will probably be played too later.

**Comment by Grey-Lancaster** [comment]
Well dat's sad.  I'd like my sound close to the strip

**Comment by T-vK** [comment]
With a smarter prediction algorithm it would probably be possible calculate when the explosions and launches happen ahead of time, but I don't think I can justify putting that much time into this project atm. If your Bluetooth device supports APTX Low Latency, you could theoretically get down to ~30ms latency, which is still a lot in my opinion, but it's probably acceptable to most eyes.

**Comment by Grey-Lancaster** [comment]
Hey, you are over my head.  If I can pair BT I am very excited LOL

**Comment by T-vK** [comment]
If you're talking about connecting the ESP with a Bluetooth speaker to play the sound effects from an SD card, you're actually gonna have a lot programming to do.

**Comment by Grey-Lancaster** [comment]
OH NO.  I was talking about pairing my speaker with my laptop.
I became the "IT Guy" at my last job because I could clear paper jams from the copier.

**Comment by T-vK** [comment]
Haha, well in that case there shouldn't be any issues other than added latency.
